global using System.Reflection;
global using AutoMapper;
global using Iems.Framework.Rest.Controllers;
global using Iems.Framework.Result;
global using Iems.Framework.Result.Values;
global using MediatR;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.Extensions.DependencyInjection;
